[package]
name = "activity_selector_dp"
version = "0.1.0"
authors = ["jleflang <jleflang@ucmerced.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
